@startuml

skinparam dpi 200
skinparam classAttributeFontSize 8
skinparam classArrowFontSize 9
skinparam classFontSize 10
skinparam nodesep 90
skinparam ranksep 40
hide stereotype
skinparam class {
	BackgroundColor LightYellow
	BackgroundColor<<Imported>> LightGrey
}

class Manifestations extends Pausable, Initializable, Evidencable {
}
class AdminUpgradeabilityProxy <<Imported>> {
}
class Pausable <<Imported>> {
}
class Initializable <<Imported>> {
}
class Evidencable {
}
class ExpirableLib {
}
class Complaints {
}
class UploadEvidences {
}
class YouTubeEvidences extends usingOraclize {
}
class usingOraclize <<Imported>> {
}
class SafeMath <<Imported>> {
}

Manifestations <-- AdminUpgradeabilityProxy
Manifestations -up-> ExpirableLib
Manifestations <-- Complaints
Evidencable <-- UploadEvidences
Evidencable <-- YouTubeEvidences
SafeMath <-- ExpirableLib
SafeMath <-- Evidencable


@enduml
